version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
    networks:
     - my-network
    depends_on:
     - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: messages
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
     - my-network
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
     - my-network
networks:
  my-network:
volumes:
  postgres-data: